"""match table

Revision ID: 4aa015daec37
Revises: b3ceb81cb733
Create Date: 2024-07-06 13:36:08.085362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa015daec37'
down_revision = 'b3ceb81cb733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=True),
    sa.Column('match_datetime', sa.DateTime(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.tournament_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_match_datetime'), ['match_datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_match_datetime'))

    op.drop_table('matches')
    # ### end Alembic commands ###
