"""tournament tables

Revision ID: 55ce0c7f6e36
Revises: 0085e79e23f9
Create Date: 2024-07-03 19:39:41.081119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ce0c7f6e36'
down_revision = '0085e79e23f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=64), nullable=True),
    sa.Column('tournament_description', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('tournament_id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_tournament_name'), ['tournament_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_tournament_name'))
        batch_op.drop_index(batch_op.f('ix_tournaments_start_date'))
        batch_op.drop_index(batch_op.f('ix_tournaments_end_date'))

    op.drop_table('tournaments')
    # ### end Alembic commands ###
