"""team users table

Revision ID: 99140b04537d
Revises: b52b4de69e48
Create Date: 2024-06-25 21:19:14.052749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99140b04537d'
down_revision = 'b52b4de69e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_users',
    sa.Column('team_user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('team_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_users')
    # ### end Alembic commands ###
