"""add teams table

Revision ID: b52b4de69e48
Revises: 4616b2046c53
Create Date: 2024-06-25 20:20:00.635658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52b4de69e48'
down_revision = '4616b2046c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('team_description', sa.String(length=500), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('official', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_team_name'), ['team_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_team_name'))

    op.drop_table('teams')
    # ### end Alembic commands ###
